### ISSUE TITLE
Unauthorized user sidebar behavior

### ISSUE THREAD

**Issue by forsureitsme** [eparraga95/dance_fit_scoreboard_front#47]
When a user token become outdated and they try to access an internal url directly(without entering through the login page), the sidebar shows a dummy `ADMIN` user.

![image](https://github.com/eparraga95/dance_fit_scoreboard_front/assets/2235293/3cf1bdef-d3ad-4e9f-bec0-55e94d42fcd0)

### Possible solution

Attach a check for 401 response status that redirects the user to login page, where they can choose to login again or enter as a guest: https://github.com/eparraga95/dance_fit_scoreboard_front/blob/c9fe6fd760d8605a0e9a1c4e095d77ae97ef5d3c/src/providers/Players/index.tsx#L135-L146

**Comment by eparraga95** [comment]
Thanks for the feedback!! That's a nice solution for now, at least way better than the one I was thinking of (setting the token's expiration to an intire year xD)
